let general = [
    "What do you want?",
    "Why are you here?",
    "Do you want to hurt us?",
    "Are you angry?",
    "Do you want us here?",
    "Shall we leave?",
    "Should we leave?",
    "Do you want us to leave?",
    "What should we do?",
    "Can we help?",
    "Are you friendly?",
    "What are you?",
    "Are you close?",
    "Can you show yourself?",
    "Give us a sign.",
    "Let us know you are here.",
    "Show yourself.",
    "Can you talk?",
    "Speak to us.",
    "Are you here?",
    "Are you with us?",
    "Anybody with us?",
    "Is anyone here?",
    "Anybody in the room?",
    "Anybody here?",
    "Is there a spirit here?",
    "Is there a Ghost here?",
    "Are you a girl?",
    "Are you a boy?",
    "Are you male?",
    "Are you female?",
    "Who are you?",
    "Who is this?",
    "Who are we talking to?",
    "Who am I talking to?",
    "Hello?",
    "What is you name?",
    "Can you give me your name?",
    "How old are you?",
    "How young are you?",
    "What is your age?",
    "When were you born?",
    "Are you a child?",
    "Are you old?",
    "Are you young?",
    "What is location?",
    "What is your gender?",
    "Are you male or female?",
    "Are you a woman?"
];

let ouijaBoard = [
    "Who did you kill?",
    "Who is your victim?",
    "What is the name of the person you killed?",
    "What is the name of the person you murdered?",
    "What is your victim?",
    "Did you murder?",
    "Who did you murder?",
    "Who died?",
    "How old are you?",
    "What is your age?",
    "Are you old?",
    "Are you young?",
    "How long have you been dead?",
    "How many years ago did you die?",
    "How long have you been here?",
    "How long ago did you die?",
    "When did you die?",
    "How many are in this room?",
    "How many people are in this room?",
    "How many people are in here?",
    "How many ghosts are in this room?",
    "How many ghosts are here?",
    "Are you alone?",
    "Are we alone?",
    "Who is here?",
    "Who is in this room?",
    "Where are you?",
    "What is your favorite room?",
    "Where is your room?",
    "What is your room?",
    "Are you here?",
    "Are you close?",
    "Are there any spirits?",
    "Are you near?",
    "Are you around?"
];

let spiritBox = [
    "Can you speak?",
    "Can you speak to us?",
    "Make a noise.",
    "Open a door.",
    "Open this door.",
    "Turn on the light.",
    "Turn off the light",
    "Are there any ghosts?",
    "Give us a sign.",
    "Show us.",
    "Let us know you are here.",
    "Do something.",
    "Is there anyone with me?",
    "Scream.",
    "Can we speak?",
    "Would like to speak to you.",
    "Is there anyone here?",
    "May I ask you?",
    "Would you like to talk?",
    "Are you the only one here?",
    "Are you waiting?",
    "Is there anything I can do?",
    "Do you know who we are?",
    "Are you happy?",
    "Are you here all the time?",
    "Are you make or female?",
    "Do you want us to leave?",
    "Can I ask you?",
    "Can you make a sound?",
    "Show us your presence.",
    "Knock something.",
    "Make a sound.",
    "open the door.",
    "Throw something.",
    "Talk to me.",
    "Talk to us.",
    "We mean you no harm.",
    "We are friends.",
    "Is this your home?",
    "I'm scared.",
    "I am scared.",
    "Scared.",
    "Scary.",
    "Spooky.",
    "Horror.",
    "Scare.",
    "Frighten.",
    "Panic.",
    "Fright.",
    "Hide.",
    "Run.",
    "Show your presence.",
    "Shoe me."
];

general = general.sort((a, b) => a > b).map(el => {
    return { question: el, category: "general" };
});
ouijaBoard = ouijaBoard.sort((a, b) => a > b).map(el => {
    return { question: el, category: "ouijaBoard" };
});
spiritBox = spiritBox.sort((a, b) => a > b).map(el => {
    return { question: el, category: "spiritBox" };
});

let questions = [].concat.apply([], [general, ouijaBoard, spiritBox]);

export default questions;