/* Ghost Tool Evidence Types */
export const ADD_EVIDENCE = "ADD_EVIDENCE";
export const REMOVE_EVIDENCE = "REMOVE_EVIDENCE";
export const ELIMINATE_EVIDENCE = "ELIMINATE_EVIDENCE";
export const REMOVE_ELIMINATED_EVIDENCE = "REMOVE_ELIMINATED_EVIDENCE";

/* Ghost Tool Notes Types */
export const ADD_GHOST_NAME = "ADD_GHOST_NAME";
export const REMOVE_GHOST_NAME = "REMOVE_GHOST_NAME";

export const ISEVERYONE = "ISEVERYONE";
export const ISALONE = "ISALONE";

export const UPDATE_SIDE_OBJECTIVE_SELECT = "UPADTE_SIDE_OBJECTIVE_SELECT";
export const UPDATE_SIDE_OBJECTIVE_CHECKBOX = "UPDATE_SIDE_OBJECTIVE_CHECKBOX";

/* RESTES */

export const RESET_EVIDENCE = "RESET_EVIDENCE";
export const RESET_NOTES = "RESET_NOTES";
export const RESET_SIDE_OBJECTIVES = "RESET_SIDE_OBJECTIVES";